
package indi.rui.study.webservice.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SysNotifyTodoWebServiceImplService", targetNamespace = "http://webservice.notify.sys.kmss.landray.com/", wsdlLocation = "http://localhost:8077/sys/webservice/notify/todo?wsdl")
public class SysNotifyTodoWebServiceImplService
    extends Service
{

    private final static URL SYSNOTIFYTODOWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SYSNOTIFYTODOWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName SYSNOTIFYTODOWEBSERVICEIMPLSERVICE_QNAME = new QName("http://webservice.notify.sys.kmss.landray.com/", "SysNotifyTodoWebServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8077/sys/webservice/notify/todo?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SYSNOTIFYTODOWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        SYSNOTIFYTODOWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public SysNotifyTodoWebServiceImplService() {
        super(__getWsdlLocation(), SYSNOTIFYTODOWEBSERVICEIMPLSERVICE_QNAME);
    }

    public SysNotifyTodoWebServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SYSNOTIFYTODOWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public SysNotifyTodoWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SYSNOTIFYTODOWEBSERVICEIMPLSERVICE_QNAME);
    }

    public SysNotifyTodoWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SYSNOTIFYTODOWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public SysNotifyTodoWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SysNotifyTodoWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ISysNotifyTodoWebService
     */
    @WebEndpoint(name = "SysNotifyTodoWebServiceImplPort")
    public ISysNotifyTodoWebService getSysNotifyTodoWebServiceImplPort() {
        return super.getPort(new QName("http://webservice.notify.sys.kmss.landray.com/", "SysNotifyTodoWebServiceImplPort"), ISysNotifyTodoWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISysNotifyTodoWebService
     */
    @WebEndpoint(name = "SysNotifyTodoWebServiceImplPort")
    public ISysNotifyTodoWebService getSysNotifyTodoWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.notify.sys.kmss.landray.com/", "SysNotifyTodoWebServiceImplPort"), ISysNotifyTodoWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SYSNOTIFYTODOWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw SYSNOTIFYTODOWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return SYSNOTIFYTODOWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
